package nl.ru.ai.draw_interface;

public enum ActionType_t {
	SELECT_DRAWABLE, DESELECT_DRAWABLE, MOVE_DRAWABLE, RESIZE_DRAWABLE, ROTATE_DRAWABLE, ADD_DRAWABLE, DELETE_DRAWABLE, CLEAR_ALL, CHANGE_LINEWIDTH, CHANGE_LINECOLOR, CHANGE_FILLCOLOR, CHANGE_TEXT, MOVE_LAYER_UP, MOVE_LAYER_DOWN
}
