package nl.ru.ai.draw_interface;

public enum Tool_t {
	NO_TOOL, SELECTION_TOOL, IMAGE_TOOL, TEXT_TOOL, LINE_TOOL, TRIANGLE_TOOL, RECTANGLE_TOOL, ELLIPSE_TOOL, RECOGNIZE_TOOL, FREEDRAW_TOOL, MOVESELECTED_TOOL, RESIZESELECTED_TOOL, ROTATESELECTED_TOOL
}
